
name: Deploy to S3 and Lambda

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: ap-northeast-2 # set this to your preferred AWS region, e.g. us-west-1
  BUCKET_NAME: search.instancetype
  CONTAINER_NAME: MY_CONTAINER_NAME # set this to the name of the container in the
  # containerDefinitions section of your task definition

jobs:
  deploy_static:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Upload static files to S3
      run: |
        aws s3 cp ./static/index.html s3://search.instancetype/index.html
        aws s3 cp ./static/searchInstanceTypePrice.js s3://search.instancetype/searchInstanceTypePrice.js


  deploy_core:
    name: Deploy to lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Compress python code to zip
      run: "zip ./serchInstance \nls\naws s3 cp serchInstance.zip s3://search.instancetype/serchInstance.zip\naws lambda update-function-code --function-name ec2InstanceTypePriceChecker --s3-bucket ${{env.BUCKET_NAME}} --s3-key serchInstance.zip\n"
